apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: martialware
  name: martialware-api
  labels:
    app: martialware-api
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: martialware-api
  template:
    metadata:
      labels:
        app: martialware-api
    spec:
      containers:
        - name: next
          image: docker.io/jwcarman/martialware-api:1.0.5 # {"$imagepolicy": "flux-system:martialware-api"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
      imagePullSecrets:
        - name: regcred
