apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: martialware
  name: martialware-spa
  labels:
    app: martialware-spa
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: martialware-spa
  template:
    metadata:
      labels:
        app: martialware-spa
    spec:
      containers:
        - name: next
          image: docker.io/jwcarman/martialware-spa:1.0.13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP