apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fynanse-api-secrets
  namespace: fynanse
spec:
  encryptedData:
    spring.datasource.password: AgBMOQmSzhhcE/MRRZCMKEAK0JiVvsQKyTpAIG5ON0kw90aW7vBRzOYK5N63tHlqZQDMxP3xWqKctaPvrsSMPkKf760976HzxLlnwNOIjzDcHaPwFZhgyY4j3866wWp0v1apj3DntpQsQdwLzjEuV7W62pjEhPO8y/vqh+L2PHr6+Xh8DRYM9sgKqADAh+xC9PyZunCpwRG23OcImLdPgqdHYRCkaT9BNhSwD0mcKt2J1MASlEQvGA6NjXwYNyg4cyV9kQ9vrYFuH1bdfb1a8YV+qHMAt1/4QusTuLlZOyRw4iD/TyknhDH2m87R17RRrhH4jEwRWte+tAupo691quFAfQ420yeKP7phBZ0G+r8o9c1fhrD28I39/E1sQKpiiirYsTLgMEvMK/Ln5VcKti+XVKKSTJuSaS8zon3uQubSX5jzU0ArY2soEQo9ktcPK4SEvjqnSXZHD4Sn0u3KUJ+VhCiP2FQEt0CcxLIW2ZAy/m70PNrRK3PRhXw4I0BSENDongXDZJluUOOVBU7Mtv4XvR4c+O+0RN5OxF2vKSEwZjOJco5McahBG4iH/MRxgjP1VxV5d0yDLfrquyqQnZyZXDyImWxdvb3z/OYqGEmX3G3A7cQyqUC9H40EJgMCZQ/sBM1jJYhuNxF6JNupzGlvZ3IAqLfsEOfi/T4mqq/2OiT2ROBxZqDoo41T34fr4Up8ebZhjdME
  template:
    metadata:
      creationTimestamp: null
      name: fynanse-api-secrets
      namespace: fynanse

