apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fynanse-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAu0stGEce3+bWRf6qamIz4lUDe8aIfvUbm6Ml9dkw+zy9qDocEdufYn3FGmaZutvKRS0iNpuj4U67bN34qfvIIpdynKhfUqoYAiAFtcGeAZydwkcx8m2gNzYEC5wy3/CGnm/4C1sSOx0G9dRAqNUukaFzm1jnkhUTdYIKLcMk+iBm877qNaOJDkDIAAsbo8l/gpY//MAs2yhEiTnLl6A/pduvtCwEfwFNpo8qHKntdyMgLKK7UgXRqCBtnnjHV8tnIN1m6bGemJSLwcwjBfdx7J2ti+J7MFC+MzNr6Wd9G3HqxTqVhYALrQmlJfRuzLmNskeErw/V0sCywxjJOyEBaCXwwLl2EjFJqs7k9k7Gog2c16GDPw/I/hkymu9KmBGZveriRKxPOuVZSDDlUsCwGrf995+/WsXLL8NlkaRULKPSWfpVYHCgu9B/NOyweWVEvPDBrZNkbiiJ8W5L+8I37r0N0g3ihuMDglIvERM5ErgXxzHP6MHXhb6x7uZ3pClz7Z7XzHj8Wih/JlE7Q//LqRyqABEGBYNq+oB0nd1UHDENsN2S41zQwPkOctUAMwKsfU+HinGtlzaS4XpK7nmXQK0VR6ERMunlETpw8dNrbrnQbCZb8PuWMKVGWA+wu9JmQOlVa+XFIX1GGP3hmMqEQKFqSTP1SQ+GcTNCfy8uMGna8hDj1AdxIJCdQlweYUv/3I3+nO4M6MSqBJALoID2Qju0HGLFa0Zky+8qIm+CsGT51q8QT2hnML21xGDBzlpz7LA1q3D7wI2i0Ta7hxtG2VpoYTLPu+myAOTt5LiF1YEimHrh33A==
  template:
    metadata:
      creationTimestamp: null
      name: fynanse-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

