---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fynanse-api
  namespace: fynanse
  labels:
    app: fynanse-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fynanse-api
  template:
    metadata:
      labels:
        app: fynanse-api
    spec:
      containers:
        - name: spring-boot
          image: docker.io/jwcarman/fynanse-api:1.0.3 # {"$imagepolicy": "fynanse:fynanse-api"}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/fynanse-api/secrets
              name: secrets-volume
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: fynanse-api-secrets
      imagePullSecrets:
        - name: fynanse-pull-secret
