apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fynanse-pull-secret
  namespace: fynanse
spec:
  encryptedData:
    .dockerconfigjson: AgANq6MS8VgfOyTHrAAz2AssNdz0+rpLUs1H3rHt3Xe4kSI8Rm/Af3NLk21BJokMeLPyxshI1Wsxl960G7EV61oHNBpKthDL8X5y2gKL3C5r/IesnPHGJJkEwKwJtNsk/zOmdh6URR5pVqQFo/FtzEKUuEvvSsQXpIlLD3I/hFFHlYUd+UHZEfcKQiAnjSMdDgK6MJGG5a2t40Cx5EqJACQbd4++ApPrbvc8ebcsiIYo1elRqC37TlaqX/zy/tEHPi1nAv5GbF2jmiZ/G3ZbwcnlsYnuBh0ekY5iquBc/brH+3FPYwIkznk6mEenot+VkGHDvU6jN66CZmNyCp9JkNmrfTL/R1YJcSk8bqg2xbV/kWzhJ32oglpOeuclofPuxD/8p7p84yzbDeLhGnQcty+WRcB1WddYcqMpuhJkOcIRNoihcyvzAlKNhTGK6MbayX9beXeRWrVQ8uBpYNTi93R7lb2F47AulnUCTWBlDfyHkrL1mRXMdPRv14kaNPE6kDU0nOYR+R7aoY4JwmjBgVxQbYUeljMGkEL3R7VRMBW8cHBOofyFAfcDvJviWajgYeJOPwrskUht+HDrATAz+oQtZJGupvPQZmvBraMKGUYXov04Ah3JvVP1m4DguW8n1JzhtcFzuETbilvL529Bi27V3ob7cU7XGSPhirMT9akpqM8MFAFZd+fG86JIY/Xpy4WCd4Y2Qhbi4H/Y1DmFz4hLQdDCawU7MyHpHVrZ5KQ6UJLpFdeHF4TIWbNB14buth9JFc4WPU/ddhTguXQwEMGTc9ZwYai9JLmPutFPvduH3pnREq4246rORAwOeQ52Px5brj+L9PDRLKAjndAPPKhCoVMqbir5Teeas5lvFil9htSEnrVF2gypIf0u0f7xi7IYXDTd0uhP2HsR6xakl/uZJw5WkE9TfeSqV3gqs8ZBayYFgjFmlDnTwg==
  template:
    metadata:
      creationTimestamp: null
      name: fynanse-pull-secret
      namespace: fynanse
    type: kubernetes.io/dockerconfigjson

