apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fynanse-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB/lZkl5L27zx/JAI8KKizIXYJixCGrbVf+AUdU9Pe4610P3U4Ew0y/udRI8Y3i52OlbzLn4RNILPpW4IZMZe8u9viN33Ov0hja7wmRpcaD5QNGp+8yvRM5F/MqmRt9LikceChPcMs+vAdRQtpaU0R35mBdA7k0YyFHyKlHGFDOrSUG618BPerrsDSQXCg1bSVl6Kiz1DCLh/jp4+kThkRy0kiODAnvQAJbUA5ZNkrwWFCxdwMc1nVVlXU0jUnwNTTFjyEvys6hXNOxncgfqWVOCcmiTNmUu0KGR4Co0zN2dkAMxr+mGt1EdSgaAQkQvAWGYiNjRnjNAT/Yk7NNvHi5GspB/rjTIGO+nlNynyyiw138wZgDJku9OwIoShhe2CfcLeehmpEM/vaEYnc1j8oeIj9dLFls4M66uGQO7rMuiUs2CuJkT8pshqV+J+6Vn+BXIVLGgMHzR64vDJ4daWPzwTTjXjlL4oT9OMgNAscQVYB2C29j9BBQWKxcCvADnqVbVgI0dztXotPB9M4BYAVc+dZp1Yvyad/gtHP1PFTxt4wOirvZQ3QEAFPZJFmv7EE3ewAA9YAEB8lF29OGVJjb1GxAe9fUl6FMgCiEEBYdC1p0rmUP41qNCgiRidrGY45W5WLI0OSZJ3l64YPKcAN7IaBhSYvg0PJQTPA8XirubCy+rAt6W1nrWc0kuC0gptRHE9OLWy5JiSHXqiPuhmaCJGXBF1PsdbJ37Kz6YDM1CfraHbrtZMbOE7EDQ06GbX5cAFb4j6a7Zibc3YiVcC1H8Go+bcPluNRu0uwmCuJhfSkotXDRj5u+aNyxaIQGyDS7LN/cB3NCW7hRYCspbuwZdHNPs6eBou48v5utCkVPavZ0SM3dnLV7IhFsBKvTpCMzkPhqEa4xHkZUJI03bGiVqa6av0HpzA==
  template:
    metadata:
      creationTimestamp: null
      name: fynanse-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

