---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-native
  labels:
    app: hello-native
spec:
  replicas: 10
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-native
  template:
    metadata:
      labels:
        app: hello-native
    spec:
      containers:
        - name: spring-boot
          image: docker.io/jwcarman/hello-native:1.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP