apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-native
  labels:
    app: hello-native
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-native
  template:
    metadata:
      labels:
        app: hello-native
    spec:
      containers:
        - name: spring-boot
          image: docker.io/jwcarman/hello-native:1.0.9 # {"$imagepolicy": "flux-system:hello-native"}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "40Mi"
            requests:
              memory: "40Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
