apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: hello-native
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-native
  policy:
    semver:
      range: 1.0.x