apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
spec:
  sourceRef:
    kind: GitRepository
    name: auto-repo
  interval: 1m
  update:
    strategy: Setters
    path: ./manifests
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxbot
        email: fluxbot@example.com
      messageTemplate: |
        An automated update from FluxBot
        [ci skip]
    push:
      branch: auto