apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- sealed-secrets-helm-repo.yml
- sealed-secrets-helm-release.yml
- image-update-automation.yml