---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-native
  labels:
    app: hello-native
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-native
  template:
    metadata:
      labels:
        app: hello-native
    spec:
      containers:
        - name: spring-boot
          image: docker.io/jwcarman/hello-native:1.0.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP